Do some hostname validity checking

diff --git a/dsa-nagios-checks/checks/dsa-check-log-age-loghost b/dsa-nagios-checks/checks/dsa-check-log-age-loghost
--- a/dsa-nagios-checks/checks/dsa-check-log-age-loghost
+++ b/dsa-nagios-checks/checks/dsa-check-log-age-loghost
@@ -29,8 +29,13 @@ usage(){
 
 host="$1"
 if [ -z "$host" ] || [ "$host" = "-h" ] ||  [ "$host" = "--help" ]; then
-	echo >&2 "$0: Usage: $0 <host>"
+	echo >&2 "Usage: $0 <host>"
 	usage 3
+fi
+
+if [ "${host/[^a-z0-9]/}" != "$host" ]; then
+	echo >&2 "$0: Invalid hostname $1"
+	exit 3
 fi
 
 ts=$(date -d 'now' +'%Y/%m/%d')
